runtime: nodejs22
service: event-collector
entrypoint: npm run gae:start:event-collector
automatic_scaling:
  max_instances: 2
  min_instances: 1
env_variables:
  NODE_ENV: production
  DATABASE_URL: YOUR_PRODUCTION_DATABASE_URL
  REDIS_URL: YOUR_REDIS_URL
  CLASSIFICATION_QUEUE_KEY: classification_jobs
